### PR TITLE
implement AddWorkDuration

### PR DESCRIPTION
**Pull request by eafzali**
Using this method you can add working days or hours to any date. so like if you want to know when will be two business days later from now.

---
This change is [Reviewable](https://reviewable.io/reviews/rickar/cal/9)

### CODE REVIEW

**Comment by rickar** [comment]
Thank you. I like the idea, but I'm not sure I understand the implementation. I think it's confusing to add arbitrary durations when counting workdays. For example, why would you want to add seconds, minutes, or hours? Some people might expect it to handle working hours in addition to days. It seems like an AddWorkdays(start time.Time, days int) would be sufficient. What do you think?

**Comment by eafzali** [comment]
Our original use case is in our email sending platform which is to let our users specify how many hours we should wait before sending out the next followup email but they also have the option to *skip weekends and holidays*, so in this case for example if the first email went out at 8PM Friday, assuming they checked *skip weekend* and they specified 12 hours wait time for the next followup the next email should go out at Monday 8AM. 
So maybe I named the function wrong, but this is the exact functionality we need.

**Comment by rickar** [comment]
Ok, that makes sense. I do think the name is what confused me or gave me a different expectation of the behavior. What about NextWorkday(start time.Time, d time.Duration)?

**Comment by eafzali** [comment]
Hmm, it's not really the Next Workday though. It's doing the exact thing as
the standard library 'Add' method does except it will skip Weekends and
Holidays.

So maybe AddSkipWeekendHoliday or AddSkipNonWorkday?

**Comment by rickar** [comment]
I guess the issue I have with the "Add" name is that in this case if you add a duration of 0 it will still go to the next non-weekend and non-holiday. That's why I thought "Next" something would be better. What about NextNormalDay(start time.Time, add time.Duration)? Sorry for the bikeshedding, I just want the name to be clear because even I'm going to forget what it does otherwise. ;-)

**Comment by eafzali** [comment]
Right, but if you are in a Work Day and Add 0 duration it won't go to the
Next Workday, right? So that might be a little confusing. I think what it's
doing is what the standard library Add does and at the same time Skipping
non working days. So if you add 0 to a holiday it's skipping part will work
and return the next Workday. So I'd like something like
AddAndSkipWeekendsAndHolidays which is tooo long so based on Go naming
conventions and best practices I still suggest something like
AddSkipWeekendHoliday or AddSkipNonWorkdays.
But yea not a big deal. Just let me know which name you are more
comfortable with and I will update my PR.

**Comment by rickar** [comment]
True, makes sense. Let's do AddSkipNonWorkdays. Thanks!

**Pull request merged**
