### PR TITLE
Added WorkDurationInRange for better estimation of working days

### PR DESCRIPTION
**Pull request by Trial97**

### CODE REVIEW

**Comment by rickar** [comment]
Thanks! Why would you use this over WorkHoursInRange or WorkdaysInRange?

**Comment by Trial97** [comment]
This one gives the exact Duration between two dates, of course excluding the holidays.

**Comment by rickar** [comment]
Ok, reading this again it looks like it's a non-inclusive range? I think that's going to be confusing when compared to WorkdaysInRange. Is there a reason for the difference?

If possible, could you rename this to WorkdaysInRangeDuration and make it use inclusive dates? The implementation could be something like `return c.WorkdaysInRange(start, end) * time.Duration(24 * time.Hour)`

**Comment by toffguy77** [comment]
guys, do you have any progress here? may I help you somehow with this pr?

**Pull request closed without merging**
